name: staticcheck
on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

jobs:
  staticcheck:
    name: "staticcheck"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - uses: WillAbides/setup-go-faster@v1.12.0
      with:
        go-version: 1.21

    - run: go install honnef.co/go/tools/cmd/staticcheck@2023.1.6

    - run: go vet .

    - run: staticcheck ./...
